package env

const (
	API_KEY_PREFIX = "API_KEY_"
	SERVER_HOST    = "SERVER_HOST"
	SERVER_PORT    = "SERVER_PORT"
	DB_USERNAME    = "DB_USERNAME"
	DB_PASSWORD    = "DB_PASSWORD"
	DB_HOST        = "DB_HOST"
	DB_PORT        = "DB_PORT"
	DB_NAME        = "DB_NAME"
)
